### PR TITLE
Bug fixes/refactor to TaskTableModel.java

### PR DESCRIPTION
**Pull request by dtapia4**
Fixed 1 critical bug, 2 other bugs and checkstyle corrections.

### CODE REVIEW

**Comment by ajkowal** [comment]
Looks good, okay to merge.

**Comment by krcarey1** [comment]
Looks good, no issues.

**Comment by dtapia4** [comment]
Merging based on reviews by Kyle and AJ

**Comment by ajkowal** [comment]
where is the survey? and for reals you did a GREAT job this class!  How did
you do on all of your labs?

On Sun, Feb 28, 2016 at 4:11 PM, dtapia4 notifications@github.com wrote:

> Merged #42
> https://github.com/cst316/spring16project-Team-El-Paso/pull/42.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cst316/spring16project-Team-El-Paso/pull/42#event-570168927
> .

## 

AJ Kowal
(480) 258-2794

**Comment by ajkowal** [comment]
nvmd found the survey lol

On Sun, Feb 28, 2016 at 6:55 PM, Mr. Kowal kowal720@gmail.com wrote:

> where is the survey? and for reals you did a GREAT job this class!  How
> did you do on all of your labs?
> 
> On Sun, Feb 28, 2016 at 4:11 PM, dtapia4 notifications@github.com wrote:
> 
> > Merged #42
> > https://github.com/cst316/spring16project-Team-El-Paso/pull/42.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/cst316/spring16project-Team-El-Paso/pull/42#event-570168927
> > .
> 
> ## 
> 
> AJ Kowal
> (480) 258-2794

## 

AJ Kowal
(480) 258-2794

**Pull request merged**
