### PR TITLE
Us 62

### PR DESCRIPTION
**Pull request by ajkowal**
please review Splash Page changes and merge. TY

### CODE REVIEW

**Comment by smbende1** [comment]
Code changes look fine, but build.number shouldn't be included.

**Comment by ajkowal** [comment]
how do i not include the build number?

On Sun, Feb 21, 2016 at 11:30 AM, smbende1 notifications@github.com wrote:

> Code changes look fine, but build.number shouldn't be included.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cst316/spring16project-Team-El-Paso/pull/32#issuecomment-186881442
> .

## 

AJ Kowal
(480) 258-2794

**Comment by smbende1** [comment]
git checkout -- filename . The -- flag tells git you are taking out a file rather than switching to a branch.

On Sun, Feb 21, 2016 at 10:31 AM -0800, "Anthony John Kowal III" <notifications@github.com<mailto:notifications@github.com>> wrote:

how do i not include the build number?

On Sun, Feb 21, 2016 at 11:30 AM, smbende1 notifications@github.com wrote:

> Code changes look fine, but build.number shouldn't be included.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/cst316/spring16project-Team-El-Paso/pull/32#issuecomment-186881442
> .

## 

AJ Kowal
(480) 258-2794

##

**Comment by ajkowal** [comment]
Sean,

So if I do git checkout -- filename .... to the build.number that will take
it away so i may commit again and then do a pull request?

On Sun, Feb 21, 2016 at 11:41 AM, smbende1 notifications@github.com wrote:

> git checkout -- filename . The -- flag tells git you are taking out a file
> rather than switching to a branch.
> 
> On Sun, Feb 21, 2016 at 10:31 AM -0800, "Anthony John Kowal III" <
> notifications@github.commailto:notifications@github.com> wrote:
> 
> how do i not include the build number?
> 
> On Sun, Feb 21, 2016 at 11:30 AM, smbende1 notifications@github.com
> wrote:
> 
> > Code changes look fine, but build.number shouldn't be included.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/cst316/spring16project-Team-El-Paso/pull/32#issuecomment-186881442
> > 
> > .
> 
> ## 
> 
> AJ Kowal
> (480) 258-2794
> 
> ## 
> 
> Reply to this email directly or view it on GitHub<
> https://github.com/cst316/spring16project-Team-El-Paso/pull/32#issuecomment-186881625
> 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cst316/spring16project-Team-El-Paso/pull/32#issuecomment-186883254
> .

## 

AJ Kowal
(480) 258-2794

**Comment by ajkowal** [comment]
What does it want me to do to fix this?!? Week 4 material, but don't
remember this being an issue and almost all the issues are flagged as
such.  Thank you.
[image: Inline image 1]

On Sun, Feb 21, 2016 at 11:48 AM, Mr. Kowal kowal720@gmail.com wrote:

> Sean,
> 
> So if I do git checkout -- filename .... to the build.number that will
> take it away so i may commit again and then do a pull request?
> 
> On Sun, Feb 21, 2016 at 11:41 AM, smbende1 notifications@github.com
> wrote:
> 
> > git checkout -- filename . The -- flag tells git you are taking out a
> > file rather than switching to a branch.
> > 
> > On Sun, Feb 21, 2016 at 10:31 AM -0800, "Anthony John Kowal III" <
> > notifications@github.commailto:notifications@github.com> wrote:
> > 
> > how do i not include the build number?
> > 
> > On Sun, Feb 21, 2016 at 11:30 AM, smbende1 notifications@github.com
> > wrote:
> > 
> > > Code changes look fine, but build.number shouldn't be included.
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/cst316/spring16project-Team-El-Paso/pull/32#issuecomment-186881442
> > > 
> > > .
> > 
> > ## 
> > 
> > AJ Kowal
> > (480) 258-2794
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/cst316/spring16project-Team-El-Paso/pull/32#issuecomment-186881625
> > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/cst316/spring16project-Team-El-Paso/pull/32#issuecomment-186883254
> > .
> 
> ## 
> 
> AJ Kowal
> (480) 258-2794

## 

AJ Kowal
(480) 258-2794

**Comment by smbende1** [comment]
It is certainly a complicated process to fix (i.e. change the files in the commit) a commit that is already pushed, at least it was the first time I did it. If there are simply additional changes, a commit --amend works, but in this case I think you have to do a git revert HEAD~0 (or HEAD~1), then checkout the build.number file, then commit again and push to replace this push. Check out some revert examples for suggested usage - I wish I had taken some notes when I did it.

Alternatively, you can Kyle or Dena to sign-off and this can be merged, then you can manually edit the build.number file and make a new commit on the master branch to fix it. I think the issue with that method is the inherent danger in making a pull request against master since the merge is done immediately with the PR. Also, if someone happened to update their master branch while that was in process, their next PR might have the bad build.number.

**Comment by dtapia4** [comment]
Are we or aren't we waiting for the build.xml to be removed from the PR?

**Comment by ajkowal** [comment]
I'd say you are waiting for the removal, will have it done after work today
I'm hoping.  Still wrapping up the lab.  BTW is it just me or did we only
have 6 labs and now we have one due on the very lasts days?

On Sun, Feb 21, 2016 at 9:16 PM, dtapia4 notifications@github.com wrote:

> Are we or aren't we waiting for the build.xml to be removed from the PR?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cst316/spring16project-Team-El-Paso/pull/32#issuecomment-186996797
> .

## 

AJ Kowal
(480) 258-2794

**Comment by ajkowal** [comment]
[image: Inline image 1]
Did it manually so no issues please, accept it and put it through to
master. TY

On Mon, Feb 22, 2016 at 10:01 AM, Mr. Kowal kowal720@gmail.com wrote:

> I'd say you are waiting for the removal, will have it done after work
> today I'm hoping.  Still wrapping up the lab.  BTW is it just me or did we
> only have 6 labs and now we have one due on the very lasts days?
> 
> On Sun, Feb 21, 2016 at 9:16 PM, dtapia4 notifications@github.com wrote:
> 
> > Are we or aren't we waiting for the build.xml to be removed from the PR?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/cst316/spring16project-Team-El-Paso/pull/32#issuecomment-186996797
> > .
> 
> ## 
> 
> AJ Kowal
> (480) 258-2794

## 

AJ Kowal
(480) 258-2794

**Comment by dtapia4** [comment]
Kyle and Sean, I do not know a lot about this.  I would prefer one of you
look at AJ's build.xml edits and confirm they are safe to merge with this
PR.  Thank you.

**Comment by ajkowal** [comment]
Can you please give the green light Kyle or Sean?  The build issue is
resolved for US-62

On Mon, Feb 22, 2016 at 9:14 PM, dtapia4 notifications@github.com wrote:

> Kyle and Sean, I do not know a lot about this. I would prefer one of you
> look at AJ's build.xml edits and confirm they are safe to merge with this
> PR. Thank you.
> 
> On Mon, Feb 22, 2016 at 6:42 PM, Anthony John Kowal III <
> notifications@github.com> wrote:
> 
> > [image: Inline image 1]
> > Did it manually so no issues please, accept it and put it through to
> > master. TY
> > 
> > On Mon, Feb 22, 2016 at 10:01 AM, Mr. Kowal kowal720@gmail.com wrote:
> > 
> > > I'd say you are waiting for the removal, will have it done after work
> > > today I'm hoping. Still wrapping up the lab. BTW is it just me or did
> > > we
> > > only have 6 labs and now we have one due on the very lasts days?
> > > 
> > > On Sun, Feb 21, 2016 at 9:16 PM, dtapia4 notifications@github.com
> > > wrote:
> > > 
> > > > Are we or aren't we waiting for the build.xml to be removed from the
> > > > PR?
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/cst316/spring16project-Team-El-Paso/pull/32#issuecomment-186996797
> > 
> > > > .
> > > 
> > > ## 
> > > 
> > > AJ Kowal
> > > (480) 258-2794
> > 
> > ## 
> > 
> > AJ Kowal
> > (480) 258-2794
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/cst316/spring16project-Team-El-Paso/pull/32#issuecomment-187492041
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cst316/spring16project-Team-El-Paso/pull/32#issuecomment-187517567
> .

## 

AJ Kowal
(480) 258-2794

**Comment by smbende1** [comment]
Looks fine - the build.number file was actually messed up by whoever updated the code for the travis-CI stuff so I'm okay with Anthony's version.

**Comment by dtapia4** [comment]
Merging based on Sean's review of code.

**Pull request merged**
