### PR TITLE
ContentPane = contentOfPane

### PR DESCRIPTION
**Pull request by ajkowal**
Ui AppFrame
Refactor
contentPane = contentOfPane
pan = panel

Start.java
Checkstyle fix for longer LOC try 2

### CODE REVIEW

**Comment by dtapia4** [comment]
Ok, I'm ready to merge, but do we need to do anything with the build.xml first?

**Comment by dtapia4** [comment]
i mean build.number

**Comment by ajkowal** [comment]
yes let me fix it like last time one set

On Sun, Feb 28, 2016 at 9:52 PM, dtapia4 notifications@github.com wrote:

> Ok, I'm ready to merge, but do we need to do anything with the build.xml
> first?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cst316/spring16project-Team-El-Paso/pull/43#issuecomment-190038363
> .

## 

AJ Kowal
(480) 258-2794

**Comment by dtapia4** [comment]
Looks good.

**Pull request merged**
