### PR TITLE
Add the initial form dialog and summary element to project

### PR DESCRIPTION
**Pull request by smbende1**
Small commit to set up the initial dialog for the Plan Summary form and the test for when it should appear. Next commit will add the remaining fields to the dialog and tie a couple of them to the element. This commit has been locally tested to ensure the program still runs and performs all current functionality.

### CODE REVIEW

**Comment by dtapia4** [comment]
Sean, I see this as an open pull request.  So...I have some questions:
- When we make changes and commit - are we supposed to be making pull
  requests too?  I thought pull requests were only done when all commits
  within a User Story have been completed.
- Or do we make pull requests with each commit, but only merge at the
  completion of all tasks related to a user story.

I will review your work at some point today - but need to know whether I
need to also be merging right now....I didn't think so.

**Comment by smbende1** [comment]
I'm pretty sure as long as everyone merges changes into their branch before another PR, the number of commits preceding it doesn't matter. I was trying for some "rhythm" but if it makes it easier I can do a single PR per user story.

**Comment by dtapia4** [comment]
Doesn't matter to me - whatever we all agree on, I will do.  I was just
looking back at Kyle's email about the process that we began for Sprint 2
and he indicated only to do a PR at the end...but maybe we don't need to
wait?  I agree that it's nice to see the work being done and to create a
flow.

**Comment by ajkowal** [comment]
I too like the flow idea with ability to better follow the thought process.

On Fri, Feb 19, 2016 at 5:17 PM, dtapia4 notifications@github.com wrote:

> Doesn't matter to me - whatever we all agree on, I will do. I was just
> looking back at Kyle's email about the process that we began for Sprint 2
> and he indicated only to do a PR at the end...but maybe we don't need to
> wait? I agree that it's nice to see the work being done and to create a
> flow.
> 
> On Fri, Feb 19, 2016 at 3:36 PM, smbende1 notifications@github.com
> wrote:
> 
> > I'm pretty sure as long as everyone merges changes into their branch
> > before another PR, the number of commits preceding it doesn't matter. I
> > was
> > trying for some "rhythm" but if it makes it easier I can do a single PR
> > per
> > user story.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/cst316/spring16project-Team-El-Paso/pull/30#issuecomment-186453195
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cst316/spring16project-Team-El-Paso/pull/30#issuecomment-186463434
> .

## 

AJ Kowal
(480) 258-2794

**Comment by dtapia4** [comment]
Closing PR until all tasks for US are completed.

**Pull request closed without merging**
